%YAML:1.0

#common parameters
imu_topic: "/imu"
image_topic: "/bebop/image_mono"
output_path: "/home/zartris/Code/Drone_MARTIN/output"

model_type: PINHOLE
camera_name: bebop-front
image_width: 856
image_height: 480
distortion_parameters:
   k1: 0.31205856
   k2: 0.23307093
   p1: -0.13151944
   p2: 0.12435412
projection_parameters:
   fx: 530.00468109
   fy: 521.86027041
   cx: 428.96714026
   cy: 248.36783979


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0  # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        


#If you choose 0 or 1, you should write down the following matrix. (IMU TO CAM)
#extrinsicRotation: !!opencv-matrix
#   rows: 3
#   cols: 3
#   dt: d
#   data: [0.0251489, 0.99861263, -0.0462639,
#           -0.24321801, 0.05100002, 0.96862996, 
#           0.96964557, -0.01310776, 0.24416317]
##Translation from camera frame to imu frame, imu^T_cam
#extrinsicTranslation: !!opencv-matrix
#   rows: 3
#   cols: 1
#   dt: d
#   data: [-0.0079632,0.11147622, -0.14677433]

## SELF CALCULATED:

#extrinsicRotation: !!opencv-matrix
#   rows: 3
#   cols: 3
#   dt: d
#   data: [ 2.4791348257715340e-02, 2.1674726129652688e-01,
#       9.7591291300608374e-01, 9.9682894975407388e-01,
#       6.8478071469890267e-02, -4.0531452724456407e-02,
#       -7.5613715579615048e-02, 9.7382307348317632e-01,
#       -2.1436228112246214e-01 ]
#extrinsicTranslation: !!opencv-matrix
#   rows: 3
#   cols: 1
#   dt: d
#   data: [ 2.3217775498957233e-01, -8.9524664682734165e-02,
#       -1.4189813302006449e-01 ]

#extrinsicRotation: !!opencv-matrix
#   rows: 3
#   cols: 3
#   dt: d
#   data: [ -4.7844696865162706e-01, -1.1232882987384357e-01,
#       8.7090225178675595e-01, 8.7725015556021058e-01,
#       -1.0518613357885798e-01, 4.6836742187338004e-01,
#       3.8995676140504421e-02, 9.8808810906816591e-01,
#       1.4886647023571553e-01 ]
#extrinsicTranslation: !!opencv-matrix
#   rows: 3
#   cols: 1
#   dt: d
#   data: [ 3.3513992440005264e-01, -2.6523403733671219e-01,
#       -1.8213643619678066e-01 ]

## CALCULATED:
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.28220108,  0.92281473, -0.26225089,
          -0.67072201, -0.00566706, -0.74168717,
          -0.68592604,  0.38520237,  0.6173529]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -0.00160873, 0.15868698, -0.34866959 ]


#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30           # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.88540990288e-01          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 2.43966847268e-02      # gyroscope measurement noise standard deviation.     #0.05
acc_w: 1.595306044560e-02    # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.16970290038e-03      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.80655     # gravity magnitude
#imu parameters       The more accurate parameters you provide, the better performance
#acc_n: 0.2         # accelerometer measurement noise standard deviation. #0.2
#gyr_n: 0.05      # gyroscope measurement noise standard deviation.     #0.05
#acc_w: 0.02    # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 4.0e-5      # gyroscope bias random work noise standard deviation.     #4.0e-5

#loop closure parameters
loop_closure: 1                 # start loop closure
load_previous_pose_graph: 0     # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1         # useful in real-time and large project
pose_graph_save_path: "/home/zartris/Code/Drone_MARTIN/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.11                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 1                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 2.60908733843e-08  # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 1        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

