%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)

Camera.fx: 5.3516773246048513e+02
Camera.fy: 5.2784121689795109e+02
Camera.cx: 4.2626125835718551e+02
Camera.cy: 2.1713515387119071e+02

Camera.k1: 4.7465342510038056e-03
Camera.k2: -1.1556249648184684e-02
Camera.p1: -1.4376921337682320e-02
Camera.p2: -8.9507819034237044e-04
Camera.k3: 0.0

Camera.width: 856
Camera.height: 480

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
